// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaKyT6Wq_Q3YENgkUjQZqZ-7meBoiTa90',
    appId: '1:359348296931:web:93f13f40738480ee27b9d6',
    messagingSenderId: '359348296931',
    projectId: 'uts-app-market',
    authDomain: 'uts-app-market.firebaseapp.com',
    storageBucket: 'uts-app-market.firebasestorage.app',
    measurementId: 'G-TVSRG7T60C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcztsj_2dek56_98qCYkWsjH1XSyz7nzw',
    appId: '1:359348296931:android:ec5eb2d653a9619127b9d6',
    messagingSenderId: '359348296931',
    projectId: 'uts-app-market',
    storageBucket: 'uts-app-market.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Qd-F1zdg0gn9m78Hzo4_e_rhFw8yiDQ',
    appId: '1:359348296931:ios:cc9bee12d4d7ff1d27b9d6',
    messagingSenderId: '359348296931',
    projectId: 'uts-app-market',
    storageBucket: 'uts-app-market.firebasestorage.app',
    iosClientId: '359348296931-7l5j21ikp3dkceihg64or0d9upaqua6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.utsAppsMarket1123150112',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Qd-F1zdg0gn9m78Hzo4_e_rhFw8yiDQ',
    appId: '1:359348296931:ios:cc9bee12d4d7ff1d27b9d6',
    messagingSenderId: '359348296931',
    projectId: 'uts-app-market',
    storageBucket: 'uts-app-market.firebasestorage.app',
    iosClientId: '359348296931-7l5j21ikp3dkceihg64or0d9upaqua6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.utsAppsMarket1123150112',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaKyT6Wq_Q3YENgkUjQZqZ-7meBoiTa90',
    appId: '1:359348296931:web:69e59384b5639beb27b9d6',
    messagingSenderId: '359348296931',
    projectId: 'uts-app-market',
    authDomain: 'uts-app-market.firebaseapp.com',
    storageBucket: 'uts-app-market.firebasestorage.app',
    measurementId: 'G-MS4NBZ24BM',
  );
}
